apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: demo-gateway
spec:
  selector:
    {{- toYaml .Values.gateway.selector | nindent 4 }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ .Values.host | quote }}
      {{- if and .Values.tls.enabled .Values.tls.httpsRedirect }}
      tls:
        httpsRedirect: true
      {{- end }}
    {{- if .Values.tls.enabled }}
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - {{ .Values.host | quote }}
      tls:
        mode: SIMPLE
        credentialName: {{ .Values.tls.secretName }}
    {{- end }}
