apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: demo-vs
spec:
  hosts:
    - {{ .Values.host | quote }}
  gateways:
    - demo-gateway
  http:
    - route:
        - destination:
            host: {{ .Values.frontend.host | quote }}
            port:
              number: {{ .Values.frontend.port }}
