replicaCount: 4

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

host: deploy.arguswatcher.net
gateway:
  namespace: istio-ingress
  name: demo-gateway

api:
  appName: demo app - shadow
  version: V6.1.0

security:
  enabled: true

shadow:
  canary:
    steps:
      - setCanaryScale:
          replicas: 2
          matchTrafficWeight: false
      - setMirrorRoute:
          name: shadow
          match:
            - method: { exact: GET }
          percentage: 100
      # Manual gate: kubectl logs -n backend -l app.kubernetes.io/name=backend-shadow \
      #     -l rollouts-pod-template-hash=<canary-hash> -f
      - pause: {}
      # remove the mirror
      - setMirrorRoute: { name: shadow }
      - setCanaryScale:
          matchTrafficWeight: true
      - setWeight: 10
      - pause: { duration: 1m }
      - setWeight: 50
      - pause: { duration: 1m }
