replicaCount: 4

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

host: deploy.arguswatcher.net
gateway:
  namespace: istio-ingress
  name: demo-gateway

api:
  appName: demo app - recreate
  version: V2.0.0

security:
  enabled: true