apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "backend-recreate.fullname" . }}
  labels:
    {{- include "backend-recreate.labels" . | nindent 4 }}
spec:
  hosts:
    - {{ .Values.host | quote }}
  gateways:
    - {{ .Values.gateway.namespace }}/{{ .Values.gateway.name }}
  http:
    - name: primary
      match:
        - uri:
            prefix: /api/
      route:
        - destination:
            host: {{ include "backend-recreate.fullname" . }}
            port:
              number: {{ .Values.service.port }}
