apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-shadow.fullname" . }}
  labels:
    {{- include "backend-shadow.labels" . | nindent 4 }}
data:
  default.conf.template: |
    log_format shadow escape=json '{'
      '"time":"$time_iso8601",'
      '"ver":"${APP_VERSION}",'
      '"method":"$request_method",'
      '"uri":"$request_uri",'
      '"status":$status,'
      '"xff":"$http_x_forwarded_for",'
      '"ua":"$http_user_agent"'
    '}';
    access_log /dev/stdout shadow;

    server {
      listen {{ .Values.service.port }};
      server_name _;

      location = /api/ {
        default_type application/json;
        return 200 '{"app":"${APP_NAME}","version":"${APP_VERSION}"}';
      }

      location = /healthz/ {
        default_type text/plain;
        return 200 'ok';
      }
    }
