{{- if .Values.security.enabled }}
apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: default
  labels:
    {{- include "backend-shadow.labels" . | nindent 4 }}
spec:
  mtls:
    mode: STRICT
{{- end }}
