replicaCount: 4

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    cpu: 100m
    memory: 64Mi

host: deploy.arguswatcher.net
gateway:
  namespace: istio-ingress
  name: demo-gateway

api:
  appName: demo app - backend-canary-multisvc
  version: V3.2.0

security:
  enabled: true

canary:
  steps:
    - setWeight: 25
    - pause: { duration: 1m }
    - setWeight: 50
    - pause: { duration: 2m }
    - setWeight: 75
    - pause: { duration: 2m }
