apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend-blue-green.fullname" . }}
  labels:
    {{- include "backend-blue-green.labels" . | nindent 4 }}
data:
  default.conf.template: |
    server {
      listen {{ .Values.service.port }};
      server_name _;

      location = /api/ {
        default_type application/json;
        return 200 '{"app":"${APP_NAME}","version":"${APP_VERSION}"}';
      }

      location = /healthz/ {
        default_type text/plain;
        return 200 'ok';
      }
    }
