apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  host: {{ include "backend.fullname" . }}
  subsets:
    - name: stable
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    - name: canary
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
