# backend-blue-green.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-02-backend-blue-green
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/simonangel-fong/argocd-argorollout-istio
    targetRevision: master
    helm:
      releaseName: backend
    path: app/backend-blue-green
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  ignoreDifferences:
    # argo-rollouts mutates weights and route destinations at runtime
    - group: networking.istio.io
      kind: VirtualService
      name: backend
      jsonPointers:
        - /spec/http
    # argo-rollouts patches rollouts-pod-template-hash into these Service selectors at runtime. 
    - group: ""
      kind: Service
      name: backend-backend-blue-green-active
      jsonPointers:
        - /spec/selector
      managedFieldsManagers:
        - argo-rollouts
    - group: ""
      kind: Service
      name: backend-backend-blue-green-preview
      jsonPointers:
        - /spec/selector
      managedFieldsManagers:
        - argo-rollouts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
